config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  resources :cats, only: ['index', 'show', 'create', 'destroy', 'update', 'new', 'edit']
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: { in: %w(black brown tabby ginger gray burgundy sandy white)}
  validates :sex, inclusion: { in: %w(M F Q)}
  def age
    ((Date.today) - birth_date).to_i/365
  end

  has_many :rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest


end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED)}
#  validate :overlapping_requests

  def overlapping_requests
    requests = cat.rental_requests
    #requests.includes(:)
    requests = requests.where({ start_date: start_date..end_date})
      .or(requests.where({ end_date: start_date..end_date}))
      .where('id != ?', id)
  end

  def overlapping_approved_requests
    overlapping_requests.select {|request| request.status == 'APPROVED'}
  end



  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat,
    dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def destroy
    @cat.destroy
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save!
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :color, :birth_date, :description, :sex)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_helper.rb
module CatHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_cat.html.erb
<h1> Name: <%= cat.name %> </h1>
<table>
    <tr>
      <td> Sex </td>
      <td> <%= cat.sex %> </td>
    </tr>
    <tr>
      <td> Colour </td>
      <td> <%= cat.color %> </td>
    </tr>
    <tr>
      <td> Age </td>
      <td> <%= cat.age %> </td>
    </tr>
    <tr>
      <td> Description </td>
      <td> <%= cat.description %>
    </tr>
</table>

app/views/cats/_form.html.erb
 <% if action == :edit %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method= 'post'>
  <% if action == :edit %>
    <input type='hidden' name='_method' value='PATCH'>
  <% end %>
  <label for='name'> Name </label>
  <input id='name' type='text' name = 'cat[name]' value="<%= action == :edit ? @cat.name : ''%>">


  <br>

  <label for='birth_date'> Birth Date </label>
  <input id='birth_date' type='date' name = 'cat[birth_date]'
   value="<%= action == :edit ? @cat.birth_date : '' %>">
  <br>
  Colour
  <select name = "cat[color]">
    <option <%= action == :edit ? '' : 'selected' %> disabled> Please Select A Color </option>

    <% %w(black brown tabby ginger gray burgundy sandy white).each do |color| %>

    <option value= "<%=color%>" <%= action == :edit && @cat.color == color  ? 'selected' : ''%> >
      <%=color%></option>
    <% end %>
</select>
  <br>
   Sex
  <select name = "cat[sex]">

    <option <%= action == :edit ? '' : 'selected' %> disabled> Please Select A Sex </option>

    <% %w(Q F M).each do |sex| %>

   <option value= "<%=sex%>" <%= action == :edit && @cat.sex == sex ? 'selected' : ''%> >
     <%=sex%></option>

    <% end %>
  </select>

  <br>
  <label for='description'> Description </label>
  <input id='description' type='text' name = 'cat[description]'
  value="<%= action == :edit ? @cat.description : '' %>"
  <br>
  <input type='submit' value = "<%= action == :edit ? 'update cat' : 'register cat' %>">
</form>

app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<%= render @cats %>

app/views/cats/new.html.erb
<%= render 'form', cat: @cat, action: 'new' %>

app/views/cats/show.html.erb
<h1> <%= render @cat %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChinMuoiChinMeo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>